import os
import hmac
import hashlib
import requests
import secrets

RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "rzp_test_earthenbeauty_demo")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "demo_secret_key_12345")


def is_demo_mode():
    return not RAZORPAY_KEY_ID or RAZORPAY_KEY_ID.startswith("rzp_test_earthenbeauty_demo")


def create_razorpay_order(amount_rupees: float, receipt_id: str, notes: dict = None) -> dict:
    """
    Create a Razorpay Order.
    amount_rupees: float (e.g., 550.0) -> converted to paise (55000)
    """
    amount_paise = int(round(amount_rupees * 100))

    if is_demo_mode():
        # Demo simulation order for testing without real credentials
        demo_order_id = f"order_demo_{secrets.token_hex(8)}"
        return {
            "id": demo_order_id,
            "amount": amount_paise,
            "currency": "INR",
            "receipt": receipt_id,
            "status": "created",
            "is_demo": True,
            "key_id": RAZORPAY_KEY_ID
        }

    # Real Razorpay API call
    try:
        url = "https://api.razorpay.com/v1/orders"
        auth = (RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET)
        payload = {
            "amount": amount_paise,
            "currency": "INR",
            "receipt": receipt_id,
            "notes": notes or {}
        }
        res = requests.post(url, json=payload, auth=auth, timeout=10)
        res.raise_for_status()
        data = res.json()
        data["key_id"] = RAZORPAY_KEY_ID
        data["is_demo"] = False
        return data
    except Exception as e:
        print(f"[Razorpay API Error] {e}")
        # Fallback to simulated order so checkout does not completely break
        demo_order_id = f"order_demo_{secrets.token_hex(8)}"
        return {
            "id": demo_order_id,
            "amount": amount_paise,
            "currency": "INR",
            "receipt": receipt_id,
            "status": "created",
            "is_demo": True,
            "key_id": RAZORPAY_KEY_ID,
            "error_note": str(e)
        }


def verify_razorpay_signature(razorpay_order_id: str, razorpay_payment_id: str, razorpay_signature: str) -> bool:
    """
    Verify payment signature generated by Razorpay.
    """
    if is_demo_mode() or razorpay_order_id.startswith("order_demo_"):
        # Automatically approve demo testing signatures
        return True

    try:
        message = f"{razorpay_order_id}|{razorpay_payment_id}".encode("utf-8")
        secret = RAZORPAY_KEY_SECRET.encode("utf-8")
        generated_signature = hmac.new(secret, message, hashlib.sha256).hexdigest()
        return hmac.compare_digest(generated_signature, razorpay_signature)
    except Exception as e:
        print(f"[Razorpay Signature Verify Error] {e}")
        return False
